### ISSUE TITLE
Why is the run command specified twice. Once in Proc and once in the manifest?

### ISSUE THREAD

**Issue by kkelly18** [kkelly18/flask-on-predix#3]
are both needed?  which one has precedence?

**Comment by futuregarnet** [comment]
I think this Predix Forum answer has the best explanation:
https://forum.predix.io/questions/2778/how-do-i-deploy-python-application-in-predix.html

tl;dr
You only need one. If you have both, the manifest.yml command properties will override the properties in the Procfile. Procfile seems to be more flexible and has more fault tolerance.
